name: Comité des Fêtes d'Auzielle
email: comitedesfetesdauzielle@gmail.com
facebook: https://www.facebook.com/CFA31650?locale=fr_FR
instagram: https://www.instagram.com/comitedauzielle/
tiktok: https://www.tiktok.com/@comitedauzielle
helloasso: https://www.helloasso.com/associations/comite-des-fetes-d-auzielle
